import { MarsMissionImage, MoonMissionImage, SpaceByte } from "./Images";

export const NavContent = [
  { name: "Home", path: "/" },
  { name: "Event Detection", path: "/event-detection" },
  { name: "Resources", path: "/resources" },
  { name: "About", path: "/about" },
];

export const cardData = [
  {
    title: "Apollo Mission",
    imageSrc: MoonMissionImage,
    description:
      "The Apollo missions were designed to land humans on the Moon and safely return them to Earth. Apollo 11, in 1969, marked the first human steps on the Moon.",
  },
  {
    title: "Mars Insight",
    imageSrc: MarsMissionImage,
    description:
      "NASA's Mars InSight mission studies Mars' seismic activity and heat flow, offering insights into the planet's structure and formation.",
  },
];


export const SeismicData = [
  {
    title: "Seismic Data",
    description1:
      "Seismic data refers to the information collected from seismic waves generated by natural events, such as earthquakes, or artificial sources, like explosions. This data is crucial in understanding the Earth's internal structure and behavior, as it provides insights into subsurface geological formations and helps in assessing seismic hazards.",
    description2:
      "By integrating seismic data with other geophysical methods, scientists can create a more comprehensive picture of the Earth's dynamics and improve their ability to predict and respond to seismic events.",
  },
];

export const footerLinks = [
  "Contact Us",
  "Privacy Policy",
  "Terms & Conditions"
];

// export const MarsBriefData = [
//   {
//     text: "lorem ipsum lorem ipsumlorem ipsumlorem ipsum lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum",
//   },
// ];

// export const MoonBriefData = [
//   {
//     text: "lorem ipsum lorem ipsumlorem ipsumlorem ipsum lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum",
//   },
// ];

export const OurTeam=[
  {
    name:"Bibek Bikram Shahi",
    role:"AI/ML Developer",
    image:SpaceByte,
  },
  {
    name:"Laya Pandey",
    role:"AI/ML Developer",
    image:SpaceByte,
  },
  {
    name:"Sanisha Kayastha Shrestha",
    role:"UI/UX Designer",
    image:SpaceByte,
  },
  {
    name:"Biranchi Kumar Shah",
    role:"Frontend Developer",
    image:SpaceByte,
  },
  {
    name:"Deepan Paudel",
    role:"Backend Developer",
    image:SpaceByte,
  },
  {
    name:"Anwit Dahal",
    role:"Frontend Developer",
    image:SpaceByte,  
  },
]
