import { SpaceByte } from "./Images";

export const NavContent = [
  { name: "Home", path: "/" },
  { name: "Event Detection", path: "/event-detection" },
  { name: "Resources", path: "/resources" },
  { name: "About", path: "/about" },
];

export const cardData = [
  {
    title: "Card Title 1",
    imageSrc: SpaceByte,
    description:
      "This is a brief description for Card Title 1. It provides a quick summary of the content or purpose of the card.",
  },
  {
    title: "Card Title 2",
    imageSrc: SpaceByte,
    description:
      "This is a brief description for Card Title 2. It provides a quick summary of the content or purpose of the card.",
  },
];

export const SeismicData = [
  {
    title: "Seismic Data",
    description1:
      "Seismic data refers to the information collected from seismic waves generated by natural events, such as earthquakes, or artificial sources, like explosions. This data is crucial in understanding the Earth's internal structure and behavior, as it provides insights into subsurface geological formations and helps in assessing seismic hazards.",
    description2:
      "By integrating seismic data with other geophysical methods, scientists can create a more comprehensive picture of the Earth's dynamics and improve their ability to predict and respond to seismic events.",
  },
];

export const footerLinks = [
  "Contact Us",
  "Privacy Policy",
  "Terms & Conditions",
];

export const MarsBriefData = [
  {
    text: "lorem ipsum lorem ipsumlorem ipsumlorem ipsum lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum",
  },
];

export const MoonBriefData = [
  {
    text: "lorem ipsum lorem ipsumlorem ipsumlorem ipsum lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum",
  },
];
